CREATE TABLE tb_job_log (
    log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主键
    proc_name      VARCHAR2(80) NOT NULL,                               -- 存储过程名称
    starttime      DATE NOT NULL,                                       -- 开始时间
    endtime        DATE NOT NULL,                                       -- 结束时间
    proc_status    VARCHAR2(10) NOT NULL,                               -- 状态 (例如: '1' 成功, '0' 失败)
    proc_desc      VARCHAR2(4000),                                      -- 描述信息或错误信息
    created_at     DATE DEFAULT SYSDATE                                 -- 记录创建时间
);

CREATE INDEX idx_tb_job_log_proc_name ON tb_job_log(proc_name);
CREATE INDEX idx_tb_job_log_starttime ON tb_job_log(starttime);
CREATE INDEX idx_tb_job_log_endtime ON tb_job_log(endtime);
CREATE INDEX idx_tb_job_log_proc_status ON tb_job_log(proc_status);